# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e73a09a71313f96539358c1d7d52d3f8"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Heals Warranty Selector"
handle = "heals-warranty-selector"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = true
